---
- name: install pip
  apt: name=python-pip
- name: install git
  apt: name=git
- name: install python-dev
  apt: name=python-dev
- name: install crypto
  apt: name=python-m2crypto
- name: install beach
  pip: name=beach
#==========================================================================
# Install some system configurations
#==========================================================================
- name: add local-lib to ldconfig
  lineinfile:
    dest: /etc/ld.so.conf
    create: yes
    state: present
    line: "/usr/local/lib"
  register: ldconfig_entries
- name: reload ldconfig
  command: ldconfig
  when: ldconfig_entries.changed
- name: update max open files in limits
  lineinfile:
    dest: /etc/security/limits.conf
    create: yes
    state: present
    line: "{{ item }}"
  with_items:
    - "* soft nofile 100000"
    - "* hard nofile 100000"
    - "root soft nofile 100000"
    - "root hard nofile 100000"
- name: update max open files in common-session
  lineinfile:
    dest: /etc/pam.d/common-session
    create: yes
    state: present
    line: "session required pam_limits.so"
- name: update max open files in sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    create: yes
    state: present
    line: "fs.file-max = 2097152"
  register: sysctl_entries
- name: reload sysctl
  command: sysctl -p
  when: sysctl_entries.changed

