---

- name: install ufw
  apt: name=ufw update_cache=yes
- name: firewall allow other beach nodes
  ufw: rule=allow from_ip={{ hostvars[item]['ansible_' + iface].ipv4.address }} direction=in
  when: hostvars[item]['ansible_' + iface].ipv4.address is defined
  with_items: "{{ groups['beach_nodes'] }}"
