---
#==========================================================================
# Setup the firewall.
#==========================================================================
- include: firewall.yaml
#==========================================================================
# Install Requirements
#==========================================================================
- name: install python-apt
  apt: name=python-apt
#==========================================================================
# Install JRE
#==========================================================================
- name: install jre ppa
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
- name: install jre
  apt: name=openjdk-8-jre  update_cache=yes
#==========================================================================
# Install Cassandra
#==========================================================================
- name: add cassandra repo
  apt_repository: repo="deb http://debian.datastax.com/community stable main" state=present
- name: add cassandra repo key
  apt_key: url=http://debian.datastax.com/debian/repo_key state=present
- name: install cassandra
  apt: name=cassandra update_cache=yes
#==========================================================================
# Configure Cassandra
#==========================================================================
- name: set cassandra cluster name
  lineinfile:
    dest: /etc/cassandra/cassandra.yaml
    regexp: '^cluster_name: .*'
    line: "cluster_name: {{ cluster_name }}"
    state: present
  register: cluster_name
- name: set cassandra cluster seeds
  lineinfile:
    dest: /etc/cassandra/cassandra.yaml
    regexp: '          - seeds: .*'
    line: '          - seeds: "{{ cassandra_cluster_seeds }}"'
    state: present
- name: restart cassandra if necessary
  service: name=cassandra state=restarted enabled=yes
  when: cluster_name.changed
- name: make sure cassandra is running
  service: name=cassandra state=started enabled=yes
