---

- name: install ufw
  apt: name=ufw update_cache=yes
- name: firewall allow http in
  ufw: rule=allow proto=tcp port=80 direction=in
- name: firewall allow other beach nodes
  ufw: rule=allow from_ip={{ hostvars[item]['ansible_' + iface].ipv4.address }} direction=in
  when: hostvars[item]['ansible_' + iface].ipv4.address is defined
  with_items: "{{ groups['beach_nodes'] }}"
- name: forward port 80 to a 8080
  iptables:
    chain: PREROUTING
    table: nat
    protocol: tcp
    destination_port: 80
    to_ports: 8080
    jump: REDIRECT