---
- include: firewall.yaml
- name: create tmp root limacharlie directory
  file: path={{ tmp_lc_root }} state=directory mode=0700 owner=lc
- name: copy beach cluster config
  copy:
    src: "{{ local_lc_root }}/{{ beach_config_file }}"
    dest: "{{ tmp_lc_root }}/{{ beach_config_file }}"
    owner: lc
- name: copy http endpoint script
  copy:
    src: "{{ local_lc_root }}/http_endpoint.py"
    dest: "{{ tmp_lc_root }}/http_endpoint.py"
    owner: lc