---

- name: install ufw
  apt: name=ufw update_cache=yes
- name: firewall allow beach-master
  ufw: rule=allow from_ip={{ limacharlie_master }} direction=in
- name: firewall allow outbound
  ufw: rule=allow to_ip=any direction=out
- name: firewall enable
  ufw: state=enabled policy=reject