---
#==========================================================================
# Setup the firewall.
#==========================================================================
- include: firewall.yaml
#==========================================================================
# Install the base Beach environment and mount the SSHFS drive.
#==========================================================================
- name: add master to host file
  lineinfile: dest=/etc/hosts line="{{ limacharlie_master }} lc-master"
- name: add master to known hosts
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa lc-master') }} lc-master"
- name: install pip
  apt: name=python-pip
- name: install git
  apt: name=git
- name: install python-dev
  apt: name=python-dev
- name: install sshfs
  apt: name=sshfs
- name: add lc user key for sshfs
  copy: src=/home/lc/.ssh/{{ item }} dest=/root/.ssh/{{ item }} mode=0400
  with_items:
    - id_rsa.pub
    - id_rsa
- name: add ssh config
  lineinfile:
    dest: /root/.ssh/config
    create: yes
    state: present
    line: "{{ item }}"
  with_items:
    - "Host lc-master"
    - "  User lc"
    - "  IdentityFile /root/.ssh/id_rsa"
- name: create root limacharlie directory
  file: path={{ lc_root }} state=directory mode=0700 owner=lc group=lc
- name: mount the sshfs file system
  command: sshfs -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,allow_other lc-master:{{ local_lc_root }} {{ lc_root }}
  args:
    creates: "{{ lc_root }}/__init__.py"
#==========================================================================
# Install the LC requirements
#==========================================================================
- name: install debconf-utils
  apt: name=debconf-utils
- name: install autoconf
  apt: name=autoconf
- name: install libtool
  apt: name=libtool
- name: install flex
  apt: name=flex
- name: install time_uuid
  pip: name=time_uuid
#==========================================================================
# Install requirements specific to certain LC actors (not core)
#==========================================================================
- name: install python-mysql
  apt: name=python-mysqldb
- name: install cassandra-driver
  pip: name=cassandra-driver
- name: install virustotal
  pip: name=virustotal
- name: install pexpect
  apt: name=python-pexpect
- name: install time_uuid
  pip: name=time_uuid
- name: get yara repo
  git: repo=https://github.com/refractionPOINT/yara.git dest=/tmp/yara
- name: compile yara
  command: "{{ item }}"
  with_items:
    - ./bootstrap.sh
    - ./configure --without-crypto
    - make
    - make install
  args:
    chdir: /tmp/yara/
    creates: /usr/local/bin/yara
- name: get yara-python repo
  git: repo=https://github.com/refractionPOINT/yara-python.git dest=/tmp/yara-python
- name: compile yara-python
  command: "{{ item }}"
  with_items:
    - python setup.py build
    - python setup.py install
  args:
    chdir: /tmp/yara-python/
    creates: /usr/local/lib/python2.7/dist-packages/*yara*
#==========================================================================
# Setup Beach node to start at boot
#==========================================================================
- name: start beach at boot
  cron: 
    special_time: reboot 
    name: beach
    user: lc
    job: "nohup python -m beach.hostmanager {{ lc_root }}/{{ beach_config_file }} --log-level {{ beach_log_level }} &"
  register: beach_cron

