---

- hosts: endpoints
  serial: 1
  become: yes
  become_user: lc
  tasks:
    - name: stop endpoint script
      shell: "pkill -f '^python .*http_endpoint.py' --signal 15"
      ignore_errors: yes
    - name: start endpoint script
      shell: "nohup python {{ tmp_lc_root }}/http_endpoint.py {{ tmp_lc_root }}/{{ beach_config_file }} 8080 &"
    - name: wait for endpoint script to connect
      shell: "sleep 10"
    