---
#==========================================================================
# Setup the firewall.
#==========================================================================
- include: firewall.yaml
#==========================================================================
# Install MySql
#==========================================================================
- name: setup the password for mysql server
  shell: "echo mysql-server mysql-server/root_password password {{ mysql_password }} | debconf-set-selections"
  args:
    creates: /etc/mysql/my.cnf
- name: setup the password confirmation for mysql server
  shell: "echo mysql-server mysql-server/root_password_again password {{ mysql_password }} | debconf-set-selections"
  args:
    creates: /etc/mysql/my.cnf
- name: install mysql server
  apt: name=mysql-server
  register: mysql_server_install
#==========================================================================
# Configure Cassandra
#==========================================================================
- name: copy over the schema
  copy: src=/home/lc/limacharlie/cloud/schema/state_db.sql dest=/tmp/state_db.sql mode=0400
- name: load mysql schema
  shell: mysql --user=root --password={{ mysql_password }} < /tmp/state_db.sql
  when: mysql_server_install.changed
- name: grow max allowed packets
  lineinfile:
    dest: /etc/mysql/my.cnf
    regexp: '.*max_allowed_packet.*'
    line: 'max_allowed_packet = 64M'
    state: present
  register: mysql_config
- name: restart mysql if necessary
  service: name=mysql state=restarted enabled=yes
  when: mysql_config.changed
- name: make sure mysql is running
  service: name=mysql state=started enabled=yes